services:
  prometheus:
    image: prom/prometheus:latest
    container_name: homelab-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana-oss:latest
    container_name: homelab-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin123}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
      - GF_FEATURE_TOGGLES_ENABLE=ngalert
    volumes:
      - grafana-data:/var/lib/grafana
    configs:
      - source: grafana_datasource
        target: /etc/grafana/provisioning/datasources/prometheus.yml
      - source: grafana_dashboards_config
        target: /etc/grafana/provisioning/dashboards/dashboards.yml
      - source: synology_dashboard
        target: /var/lib/grafana/dashboards/synology-nas-dashboard-new.json
      - source: rag_dashboard
        target: /var/lib/grafana/dashboards/rag-stack-dashboard.json
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - prometheus

  # Optional: Node Exporter for host system monitoring
  node-exporter:
    image: prom/node-exporter:latest
    container_name: homelab-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring
    restart: unless-stopped

  # Optional: cAdvisor for container monitoring
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: homelab-cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
    privileged: true
    networks:
      - monitoring
    restart: unless-stopped

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  monitoring:
    driver: bridge

configs:
  prometheus_config:
    file: ./monitoring/prometheus.yml
  grafana_datasource:
    file: ./monitoring/grafana/provisioning/datasources/prometheus.yml
  grafana_dashboards_config:
    file: ./monitoring/grafana/provisioning/dashboards/dashboards.yml
  synology_dashboard:
    file: ./monitoring/grafana/dashboards/synology-nas-dashboard-new.json
  rag_dashboard:
    file: ./monitoring/grafana/dashboards/rag-stack-dashboard.json
