global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'homelab'
    replica: 'prometheus-01'

rule_files:
  # - "alert_rules.yml"
  # - "recording_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Node Exporter for host system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # External services monitoring
  # Add your external services here
  # Example: Synology NAS
  - job_name: 'synology-nas'
    metrics_path: /metrics
    static_configs:
      - targets: ['${SYNOLOGY_IP:-192.168.1.131}:3001']
        labels:
          instance: 'synology-nas'
          service: 'nas'
    scrape_interval: 30s

  # Example: Other homelab services
  # - job_name: 'homelab-services'
  #   static_configs:
  #     - targets: 
  #         - '192.168.1.100:9100'  # Another node exporter
  #         - '192.168.1.101:9100'  # Another node exporter
  #   scrape_interval: 30s

  # Service discovery for Docker containers (if using docker_sd_configs)
  # - job_name: 'docker-containers'
  #   docker_sd_configs:
  #     - host: unix:///var/run/docker.sock
  #       refresh_interval: 30s
  #   relabel_configs:
  #     - source_labels: [__meta_docker_container_name]
  #       target_label: container_name
  #     - source_labels: [__meta_docker_container_label_com_docker_compose_service]
  #       target_label: compose_service
